services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   environment:
    DDB_LOCAL_TELEMETRY: 0
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal

 app-node:
  depends_on:
    - dynamodb-local
  image: amazon/aws-cli:latest
  container_name: app-node
  ports:
  - "8080:8080"
  environment:
    AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
    AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
  command:
    dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region eu-central-1