openapi: "3.0.1"
info:
  title: "Products"
  version: "2023-11-26T08:33:28Z"
servers:
- url: "https://rro55xf8w3.execute-api.eu-central-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /products/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "404 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OneProductModel"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
  /products:
    get:
      responses:
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllProductsModel"
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestProductModel"
        required: true
      responses:
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductErrorModel"
        "201":
          description: "201 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OneProductModel"
    options:
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  schemas:
    RequestProductModel:
      title: "ProductDao"
      required:
      - "count"
      - "description"
      - "price"
      - "title"
      type: "object"
      properties:
        price:
          type: "integer"
        count:
          type: "integer"
        description:
          type: "string"
        title:
          type: "string"
    OneProductModel:
      title: "Product"
      required:
      - "count"
      - "description"
      - "id"
      - "price"
      - "title"
      type: "object"
      properties:
        price:
          type: "integer"
        count:
          type: "integer"
        description:
          type: "string"
        id:
          type: "string"
        title:
          type: "string"
    AllProductsModel:
      title: "Products"
      type: "array"
      items:
        $ref: "#/components/schemas/OneProductModel"
    ProductErrorModel:
      title: "Error"
      required:
      - "message"
      type: "object"
      properties:
        message:
          type: "string"
